[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "../lib"}
sqlite = "0.36.0"
log = "0.4.21"
simplelog = "0.12.2"
tokio = {version = "1.37.0", features = ["full"]}